kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: SetMultipleVariables
      id: action-1764298391675
      assignments:
        - variable: Local.current_date_time
          value: =Now()
        - variable: Local.all_learnings
          value: =""
        - variable: Local.current_iteration
          value: =0
        - variable: Local.depth
          value: =1
        - variable: Local.breadth
          value: =1
        - variable: Local.enriched_query
          value: =""
        - variable: Local.serp_queries
          value: ={}
        - variable: Local.query_index
          value: =0
        - variable: Local.query_loop_status
          value: =""
        - variable: Local.current_query
          value: =""
        - variable: Local.current_research_goal
          value: =""
        - variable: Local.web_search_results
          value: =""
        - variable: Local.learnings_response
          value: ={}
        - variable: Local.latest_followups
          value: =[]
        - variable: Local.all_iteration_followups
          value: =""
        - variable: Local.iteration_status
          value: ""
        - variable: Local.clarifying_qa_iterator
          value: =0
        - variable: Local.serp_input_message
          value: =""
        - variable: Local.all_sources
          value: =""
    - kind: Question
      variable: Local.research_query
      id: action-1764304546557
      entity: StringPrebuiltEntity
      skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
      prompt: |-
        🔬 Welcome to DeepResearch!

        What would you like to research?

        Please provide a detailed description of the topic.
    - kind: Question
      variable: Local.depth
      id: question-depth
      entity: NumberPrebuiltEntity
      skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
      prompt: |-
        📊 **Research Depth**

        How many research iterations would you like? (1-5 recommended)

        Higher depth = more thorough research but takes longer.
    - kind: Question
      variable: Local.breadth
      id: question-breadth
      entity: NumberPrebuiltEntity
      skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
      prompt: |-
        🔍 **Research Breadth**

        How many search queries per iteration? (1-5 recommended)

        Higher breadth = wider coverage but takes longer.
    - kind: SetVariable
      id: action-1764393727060
      variable: Local.enriched_query
      value: '=Concatenate("Original Query: ", Local.research_query, Char(10), Char(10))'
    - kind: SetVariable
      id: set-clarifying-input-message
      variable: Local.clarifying_input_message
      value: =Concatenate("Today is ", Text(Local.current_date_time, "yyyy-mm-dd"), ".", Char(10), Char(10), "Given the following query from the user, ask some follow up questions to clarify the research direction. Return a maximum of 3 questions, but feel free to return less if the original query is clear:", Char(10), Char(10), "<query>", Local.research_query, "</query>")
    - kind: InvokeAzureAgent
      id: action-1764245863942
      agent:
        name: ClarifyingQuestionsAgent
      input:
        messages: =Local.clarifying_input_message
      output:
        autoSend: false
        responseObject: Local.clarifying_response
    - kind: SetVariable
      id: action-1764390494378
      variable: Local.total_questions
      value: =CountRows(Local.clarifying_response.questions)
    - kind: SendActivity
      activity: "Total question: {Local.total_questions}"
      id: action-1764390358191
    - kind: ConditionGroup
      conditions:
        - condition: =((Local.total_questions > 0)&& (Local.clarifying_qa_iterator < Local.total_questions))
          actions:
            - kind: SetVariable
              id: action-1764389651916
              variable: Local.clarifying_qa_iterator
              value: =Local.clarifying_qa_iterator + 1
            - kind: Question
              variable: Local.current_clarifying_answer
              id: action-1764389674930
              entity: StringPrebuiltEntity
              skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
              prompt: "{Index(Local.clarifying_response.questions, Local.clarifying_qa_iterator).Value}"
            - kind: SetVariable
              id: action-combine-enriched-query
              variable: Local.enriched_query
              value: |-
                =Concatenate(Local.enriched_query,Char(10),
                  "Q",Local.clarifying_qa_iterator,": ", Index(Local.clarifying_response.questions, Local.clarifying_qa_iterator).Value, Char(10),
                  "A",Local.clarifying_qa_iterator,": ", Local.current_clarifying_answer , Char(10)
                )
            - kind: GotoAction
              actionId: check-clarifying-question-exist-and-iterator-valid
              id: action-1764389738300
          id: if-action-questions-greater-0
      id: check-clarifying-question-exist-and-iterator-valid
      elseActions: []
    - kind: SendActivity
      activity: "Enriched queries: {Local.enriched_query}"
      id: action-1764391265761
    - kind: InvokeAzureAgent
      id: action-1764305887884
      agent:
        name: ReportTitleAgent
      input:
        messages: =Local.enriched_query
      output:
        autoSend: false
        responseObject: Local.report_info
    - kind: SendActivity
      activity: |-
        # 📋 Research Started
            
            **Title:** {Local.report_info.title}
            **Description:** {Local.report_info.description}
            
            **Research configuration:**
            - Depth: {Local.depth} iterations
            - Breadth: {Local.breadth} queries per iteration
      id: action-1764305989123
    - kind: SetVariable
      id: research_iteration
      variable: Local.iteration_status
      value: ="checking"
    - kind: ConditionGroup
      conditions:
        - condition: =Local.current_iteration >= Local.depth
          actions:
            - kind: SendActivity
              activity: ✅ Research complete! Generating final report with learnings...
              id: notify_generating_report
            - kind: SetVariable
              id: set_report_input_message
              variable: Local.report_agent_message
              value: =Concatenate("Today is ", Text(Local.current_date_time, "yyyy-mm-dd"), ".", Char(10), Char(10), "<prompt>", Local.enriched_query, "</prompt>", Char(10), Char(10), "Here are all the learnings from previous research:", Char(10), Char(10), "<learnings>", Char(10), "<learning>", Substitute(Trim(Local.all_learnings), Char(10), Concatenate("</learning>", Char(10), "<learning>")), "</learning>", Char(10), "</learnings>", Char(10), Char(10), "Here are all the sources referenced during research:", Char(10), Char(10), "<sources>", Char(10), Trim(Local.all_sources), Char(10), "</sources>")
            - kind: InvokeAzureAgent
              id: invoke_report_agent
              agent:
                name: ReportAgent
              input:
                messages: =Local.report_agent_message
              output:
                autoSend: true
            - kind: EndConversation
              id: action-1764408312946
          id: check_reched_condition
      id: check_depth_reached
      elseActions:
        - kind: SetVariable
          id: increment_iteration
          variable: Local.current_iteration
          value: =Local.current_iteration + 1
        - kind: SetVariable
          id: reset_iteration_followups
          variable: Local.all_iteration_followups
          value: =""
        - kind: SendActivity
          activity: |-
            🔄 **Research Iteration {Local.current_iteration} of {Local.depth}**

            Generating search queries...
          id: notify_iteration
        - kind: SetVariable
          id: create_serp_input
          variable: Local.serp_input_message
          value: =Concatenate("Today is ", Text(Local.current_date_time, "yyyy-mm-dd"), ".", Char(10), Char(10), "Given the following prompt from the user, generate a list of SERP queries to research the topic.", Char(10), "Reduce the number of words in each query to its keywords only.", Char(10), "Return a maximum of ", Text(Local.breadth), " queries, but feel free to return less if the original prompt is clear. Make sure each query is unique and not similar to each other:", Char(10), Char(10), "<prompt>", Local.enriched_query, "</prompt>", If(Len(Local.all_learnings) > 0, Concatenate(Char(10), Char(10), "Here are some learnings from previous research, use them to generate more specific queries:", Char(10), Local.all_learnings), ""))
        - kind: InvokeAzureAgent
          id: serp_query_agent
          agent:
            name: SERPQueryAgent
          input:
            messages: =Local.serp_input_message
          output:
            autoSend: false
            responseObject: Local.serp_queries
        - kind: SendActivity
          activity: 📝 Generated {CountRows(Local.serp_queries.queries)} search queries
          id: notify_queries_generated
        - kind: SetVariable
          id: init_query_index
          variable: Local.query_index
          value: =0
        - kind: ConditionGroup
          conditions:
            - condition: =((CountRows(Local.serp_queries.queries) > 0) && (Local.query_index < CountRows(Local.serp_queries.queries)))
              actions:
                - kind: SetVariable
                  id: increment_query_index
                  variable: Local.query_index
                  value: =Local.query_index + 1
                - kind: SetVariable
                  id: set_current_query
                  variable: Local.current_query
                  value: =Index(Local.serp_queries.queries, Local.query_index).Value
                - kind: SetVariable
                  id: get_current_research_goal
                  variable: Local.current_research_goal
                  value: =Index(Local.serp_queries.research_goals, Local.query_index).Value
                - kind: SendActivity
                  activity: "🔍 Searching ({Local.query_index}/{CountRows(Local.serp_queries.queries)}): {Local.current_query}"
                  id: notify_searching
                - kind: SetVariable
                  id: create_websearch_input_message
                  variable: Local.current_query_research_goal
                  value: '=Concatenate("Query: ", Local.current_query, Char(10), "Research Goal: ", Local.current_research_goal)'
                - kind: InvokeAzureAgent
                  id: invoke_websearch
                  agent:
                    name: WebSearchAgent
                  input:
                    messages: =Local.current_query_research_goal
                  output:
                    autoSend: false
                    messages: Local.web_search_results
                - kind: SetVariable
                  id: create_input_learning_agent_message
                  variable: Local.current_learning_query
                  value: '=Concatenate("Today is ", Text(Local.current_date_time, "yyyy-mm-dd"), ".", Char(10), Char(10), "Given the following contents from a SERP search for the query:", Char(10), "<query>", Local.current_query, "</query>", Char(10), Char(10), "Research Goal: ", Local.current_research_goal, Char(10), Char(10), "<contents>", Char(10), Concat(Local.web_search_results, Text, Char(10)), Char(10), "</contents>")'
                - kind: InvokeAzureAgent
                  id: invoke_learning
                  agent:
                    name: LearningsAgent
                  input:
                    messages: =Local.current_learning_query
                  output:
                    autoSend: false
                    responseObject: Local.learnings_response
                - kind: SetVariable
                  id: accumulate_learnings
                  variable: Local.all_learnings
                  value: =Concatenate(Local.all_learnings, Concat(Local.learnings_response.learnings, Value, Char(10)), Char(10))
                - kind: SetVariable
                  id: store_followups
                  variable: Local.latest_followups
                  value: =Local.learnings_response.follow_up_questions
                - kind: SetVariable
                  id: accumulate_followups
                  variable: Local.all_iteration_followups
                  value: =Concatenate(Local.all_iteration_followups, Concat(Local.learnings_response.follow_up_questions, Value, Char(10)), Char(10))
                - kind: SetVariable
                  id: accumulate_sources
                  variable: Local.all_sources
                  value: =Concatenate(Local.all_sources, Concat(Local.learnings_response.sources, Value, Char(10)), Char(10))
                - kind: GotoAction
                  actionId: query_loop_condition
                  id: loop_back_to_query_loop
              id: if_more_queries
          id: query_loop_condition
          elseActions:
            - kind: SetVariable
              id: update_enriched_query
              variable: Local.enriched_query
              value: =Concatenate(Local.enriched_query, Char(10), Char(10), "Follow-up Questions for Next Iteration:", Char(10), Trim(Local.all_iteration_followups))
            - kind: GotoAction
              actionId: research_iteration
              id: loopback-research-iteration
id: ""
name: Deep-Research
description: ""
